INSERT INTO USER (username,password) VALUES ('Mert','abc123')
INSERT INTO USER (username,password) VALUES ('John','wick')
INSERT INTO USER (username,password) VALUES ('Robert','healty')
INSERT INTO USER (username,password) VALUES ('Chris','superstar')
INSERT INTO USER (username,password) VALUES ('Merve','abicige')
INSERT INTO USER (username,password) VALUES ('Senay','harrika')
INSERT INTO USER (username,password) VALUES ('Billy','russo')
INSERT INTO USER (username,password) VALUES ('Frank','Castle')
INSERT INTO FILM (description,length,name) VALUES('Some gunshot and all you know.',123,'Sashas Dream')
INSERT INTO FILM (description,length,name) VALUES('One day Bobbi wakes up as being a star. Now she is a star, she is the Star,who else could tell the otherwise?.',123,'Bobbi is a Star')
INSERT INTO FILM (description,length,name) VALUES('Faye was using RegioJet and she suddenly reacted!',123,'Faye Reacted')
INSERT INTO FILM (description,length,name) VALUES('Felegin carkina comak sokan Cem Karaca.',123,'Felek')
